# Generated by Django 4.2.1 on 2023-05-12 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("summary_text", models.CharField(max_length=200)),
                ("reported_date", models.DateTimeField(verbose_name="Reported")),
            ],
        ),
    ]
