# Generated by Django 4.2.1 on 2023-06-20 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("Open", "Open"),
                    ("In progress", "In Progress"),
                    ("Waiting for support", "Waiting For Support"),
                    ("Waiting for customer", "Waiting For Customer"),
                ],
                default="Open",
                max_length=30,
            ),
        ),
    ]
