# Generated by Django 4.2.1 on 2023-06-23 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0002_ticket_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="details_text",
            field=models.CharField(default="Details here.", max_length=500),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("Open", "Open"),
                    ("Closed", "Closed"),
                    ("In progress", "In Progress"),
                    ("Waiting for support", "Waiting For Support"),
                    ("Waiting for customer", "Waiting For Customer"),
                ],
                default="Open",
                max_length=30,
            ),
        ),
    ]
